"""empty message

Revision ID: 70a74cf8eff1
Revises: 084379a2a26a
Create Date: 2024-03-26 22:11:42.464014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a74cf8eff1'
down_revision = '084379a2a26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imgUrl', sa.String(), nullable=True),
    sa.Column('createdAt', sa.Date(), nullable=True),
    sa.Column('updatedAt', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('imgUrl', sa.String(), nullable=False),
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=True),
    sa.Column('updatedAt', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['typeId'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('exerciseId', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=True),
    sa.Column('updatedAt', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['exerciseId'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_comments')
    op.drop_table('exercises')
    op.drop_table('types')
    # ### end Alembic commands ###
